# Generated by Django 3.0.6 on 2020-05-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollNo', models.CharField(max_length=500)),
                ('ans_no_1', models.CharField(max_length=1000)),
                ('ans_no_2', models.CharField(max_length=1000)),
                ('ans_no_3', models.CharField(max_length=1000)),
                ('ans_no_4', models.CharField(max_length=1000)),
                ('ans_no_5', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MathTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('Sub', models.CharField(max_length=500)),
                ('q_no_1', models.CharField(max_length=1000)),
                ('q_no_2', models.CharField(max_length=1000)),
                ('q_no_3', models.CharField(max_length=1000)),
                ('q_no_4', models.CharField(max_length=1000)),
                ('q_no_5', models.CharField(max_length=1000)),
            ],
        ),
    ]
